services:
  circles-diy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6969:8080
    environment:
      - PORT=8080
      - TZ=Australia/Sydney
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    # no-new-privileges breaks Go binary execution
    tmpfs:
      - /tmp:nosuid,size=100m
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  feedback_data:
    driver: local